### ISSUE TITLE
Unable to request client credentials.

### ISSUE THREAD

**Issue by a8b** [ello/ello-ios#10]
> If you would like to run the iOS app, please contact us for client credentials.

Doesn't work. 

```
A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

 ios@ello.co
   host aspmx.l.google.com

```

**Comment by jindulys** [comment]
Me too, I met with the same issue. Hope this could be resolved.

**Comment by steam** [comment]
@a8b and @jindulys, good catch. We forgot to set this email up. It should be good to go now. We're excited about your interest in getting access, we'll need to talk internally about what that looks like. Please try sending those emails again.
