### ISSUE TITLE
Why not FutureKit??

### ISSUE THREAD

**Issue by colinta** [ello/ello-ios#112]
Our API responses all have the pattern `Service().apiCall(params, success: { obj in }, failure: { error in })`, wich is pretty *darned close* to `Service().apiCall(params).onSuccess { obj in }.onFail { error in }` (aka FutureKit's API).

**Comment by colinta** [comment]
I'd like to experiment / demo this idea in [`cg/add/hire-me-button`](https://github.com/ello/ello-ios/tree/cg/add/hire-me-button).

**Comment by steam** [comment]
I like the idea quite a bit. The chainable trailing closure syntax is nice.

**Comment by colinta** [comment]
FutureKit has been great so far - though we should make sure we prefer it over PromisesKit.
