### ISSUE TITLE
Storing user password in keychain

### ISSUE THREAD

**Issue by wecodenow** [ello/ello-ios#153]
I'm curious why you guys are storing the user's password in the keychain and on the `AuthToken` struct? I've been studying your codebase a lot and have learned so much from it so thank you.. but there are some things that are still confusing to me.
1. Am I correct in assuming that you're simply sending the password to the server without hashing it or encrypting it? It looks like you only hash the contact phone numbers. I realize you are using SSL, but still I was under the assumption that when you sent data like a password up to the server you weren't supposed to send it as plain text. Please correct me if I'm wrong.
2. Why the need to store the password in the keychain at all, isn't the username combined with the `access_token` and `refresh_token` enough? I noticed the password is used for signup (join) and login (auth). If the user has a `refresh_token` at all, isn't that enough to gain a new `access_token` on its own?

I just got started with backend dev and I'm using some similar things to you guys, but I'm not storing the password in the keychain. All I store is the `access_token` (and soon the `refresh_token`). The tokens alone can be used for re-authenticating and allowing the user to continue to hit protected API endpoints since the token/JWT contains the user's unique id for authentication. The only time the user's password is needed is on signup and login, and they only see the login screen after logging out, deleting the app off their phone, etc.

I feel like I am misunderstanding something here, but I am very close so really appreciate the help.

**Comment by colinta** [comment]
Hey there!

1. AFAIK, web services and other external API consumers routinely send passwords in plain text, and then the server hashes them when it compares them to the stored password (which is also hashed).  The reason you cannot hash them from the client is because (at least on web) that would expose the secret and unique hashing salts.

2. Ideally, you're right, and we wouldn't need to store the username and password, and just rely on the refresh token.  In "real world dev", this scenario breaks down when multiple in-flight requests are sent to the server, each one tries to refresh the token, some madness ensues, and the *valid* refresh token gets lost.  In that case we fallback to the username and password, so the user experience is pristine.  The Apple Keychain is built for this purpose, so I don't think we're crossing dangerous lines relying on that.

Good points, though!

**Comment by rlam3** [comment]
@wecodenow I'm also in your position as well. I'm also trying to figure out how to best utilize JWT when creating the API for my app. Authentication is a really tricky subject, especially when you are dealing with token expirations. I think you are correct for the most part. 

@colinta Even if a token were to get lost/revoked/expired. Shouldn't the user necessarily be logging back into the app? 

I think this is a good discussion topic for most people who are trying to understand what is best practice for storing and refreshing tokens or using username and password. 

Reference: 

http://stackoverflow.com/questions/33645173/token-based-authentication-from-a-mobile-app

**Comment by colinta** [comment]
You'll need to make this call based on your own app requirements, user experience, etc.  We decided to trust Apple's keychain storage (and we were already using it to store the client id, client secret, and refresh token) to improve the user experience around "sudden logout", which was *very undesireable*.

**Comment by mitchellporter** [comment]
This is a really good question that, like many things in programming, doesn't have a "perfect" answer. You just have to weigh the pros and cons of each path and choose one. There is a really good StackOverflow discussion on this that I have favorited I'll try and find it.

**Comment by mitchellporter** [comment]
>...In that case we fallback to the username and password, so the user experience is pristine.

What is the fallback process like? Do you just grab the username and password from the keychain and do a programmatic login on behalf of the user, and then you end up getting a new access token and refresh token as well?

>You'll need to make this call based on your own app requirements, user experience, etc. We decided to trust Apple's keychain storage (and we were already using it to store the client id, client secret, and refresh token) to improve the user experience around "sudden logout", which was very undesireable.

FWIW I use the same setup that ello is using and enjoy using it. A good balance of security and usability for the user.
