### ISSUE TITLE
Do categories, links and totalViewCount belong on User or Profile?

### ISSUE THREAD

**Issue by steam** [ello/ello-ios#182]
I'm starting this conversation here so we have a centralized place to discuss the pros and cons.

While implementing the changes to the user profile screen I had to decide where `categories`, `externalLinks` and `totalViewCount` belong, on `User` or `Profile`. Relatively quickly @colinta pointed out that `Profile` is only loaded for the current user so we'll need to add/update the properties on `User`. 

The next decision to make is wether or not we should send all three properties back on every user, in every scenario. Currently we provide everything necessary to render a user's profile every time we serialize a `User` server-side. This allows us to display a user's profile immediately when a username or avatar is tapped in a stream. With profiles 2.0 we have user cards with featured category badges and user profile detail views with structured social links and total view count. we would need those properties present on every user, even users serialized as `links` when viewing your following, starred or discover screens for example.

Does providing the external links (with matched social icons), featured categories and total view count on every `User` seem reasonable @jayzes? If not, we'll need to reassess the assumptions we make when displaying a user's profile. Namely, that having the `User` is enough information. `ProfileGenerator` assumes that it is. We could potentially show what we have and stage the loading of total view count, featured categories and/or links. I'm not sure how that would work visually though. 

Please add comments. cc/ @Justin-Holmes @colinta @jayzes

**Comment by jayzes** [comment]
I think we'd want to figure out how to package those into the base `User` response for sure - it shouldn't be much more expensive on the server side, and it would make things a lot easier to reason about.

**Comment by rynbyjn** [comment]
On the web we expect all of those properties to be there whenever we have a user object.

**Comment by steam** [comment]
`User` it is. `Profile` is for the logged in user, not other users.
