### ISSUE TITLE
Specifying multiple `post_install` hooks is unsupported..

### ISSUE THREAD

**Issue by drewcrawford** [ello/ello-ios#200]
When attempting to run `pod install`, I get as follows:

```
[!] Invalid `Podfile` file: [!] Specifying multiple `post_install` hooks is unsupported..

 #  from /Users/drew/Code/ello-ios/Podfile:103
 #  -------------------------------------------
 #
 >  post_install do |installer|
 #    installer.pods_project.targets.each do |target|
 #  -------------------------------------------
```

**Comment by steam** [comment]
Hi @drewcrawford, I just ran a clean clone and `pod install` and did not run into this issue. What version of CocoaPods are you using? `pod --version` outputs 1.0.1 for me. I usually run `bundle exec pod install`. You might try that as well.

**Comment by steam** [comment]
I run ruby 2.2.2 for this project. Do you use either `rvm` or `rbenv`? The `.ruby-version` file is used by `rbenv` to load the correct ruby. If you don't use either tool make sure you are running ruby 2.2.2. What does `ruby --version` output?

**Comment by steam** [comment]
We'd like too be CocoaPods 1.1.1 compliant, we just haven't updated our Podfile yet. The dependency dance can be a bit of a pain.

**Comment by drewcrawford** [comment]
After downgrading to cocoapods 1.0.1 I was able to `pod install` successfully.  I also needed to make a change in https://github.com/ello/ElloOSSUIFonts/pull/2.

Now however I am faced with

```
/Users/drew/Code/ello-ios/Sources/Model/ElloKeychain.swift:31:35: Value of type 'ElloKeys' has no member 'teamId'
```

and indeed, consulting the [podfile](https://github.com/ello/ello-ios/blob/master/Podfile#L92) suggests such a key does not exist.  Should I add it locally?

**Comment by steam** [comment]
Thanks for continuing down this path. Do you have a `.env` file? `cp .env-example .env`. Once you have `.env` with the proper oauth credentials and server you run `bundle exec rake generate:staging_keys`. I believe that the error will go away. It does look like `teamId` is missing from the Podfile though. Adding it may be required (although that is the same Podfile we use internally and we do not see the error).

**Comment by drewcrawford** [comment]
Thanks, after building ruby 2.2.2 from source and running that command I was able to build.
