### ISSUE TITLE
Come up with a new header to replace the lame copyright

### ISSUE THREAD

**Issue by colinta** [ello/ello-ios#45]
@steam Rather than just delete the file header/copyright, we could have something interesting at the top - and include the filename there.  My preference would be to keep it short.

Something like this:

```swift
////
///  Whatever.swift
//

class Whatever {
}
```

**Comment by AndrewSB** [comment]
@colinta are you familiar with the implications of removing the copyright notice at the top of each source file?

I'm assuming they mean nothing, since they are completely absent in code not authored by Xcode? So as long as the repository has a license, the copyright notice means nothing?

**Comment by colinta** [comment]
Exactly - as long as the relationship between code and code owner is clear (and actually, github makes that relationship much more obvious), I don't think a per-file copyright is necessary.

**Comment by steam** [comment]
@colinta are you thinking we need something at the top so we don't have the type name jammed up against the top of the file?

**Comment by colinta** [comment]
Yup, exactly.  Could even just be ```/////////////// Filename.swift``` - I guess I like *something* more than nothing.  And it creates a place for notes, should they be necessary (hopefully not, those "doc strings" are sometimes the first to become stale).

**Comment by steam** [comment]
```
////
///  Whatever.swift
//
``` 

Looks pretty good to me. 👍

**Comment by AndrewSB** [comment]
Once you guys do this, can you share the script you end up using?
I've looked into using `sed` to remove the lines, but I didn't spend long enough to get it to work

**Comment by colinta** [comment]
It's already done, we just used a regex search and replace:

```regex
//
//  (.*)
//  Ello
//
//  Created by.*
//  Copyright.*
//
```

```
////
///  $1
//
```

**Comment by AndrewSB** [comment]
thanks for sharing!
