### ISSUE TITLE
(re) Integrate CI

### ISSUE THREAD

**Issue by steam** [ello/ello-ios#5]
In the process of moving the repo into the open our automated hooks got 'un' hooked up.

**Comment by colinta** [comment]
Something fishy going on with Travis (it's not seeing the private repo or this public one), so I tweeted them, hopefully resolved soon.

**Comment by steam** [comment]
Did you see @jayzes note yesterday? 
```
deprovision it on travis-ci.com and re-do it on travis-ci.org
```

Did you give that a go?

**Comment by colinta** [comment]
Yeah that's already done.  `ello-ios` is still appearing on travis-ci.com, and `ello-ios-private` is *not*, and neither are on travis-ci.org.
