### ISSUE TITLE
Blog about your experience of open sourcing.

### ISSUE THREAD

**Issue by jcampbell05** [ello/ello-ios#52]
Hey I run a blog for @supmenow and was wondering if you would be open to doing a guest post on your experience in open sourcing Ello?

It would be something that would be super interesting for us.

**Comment by steam** [comment]
Hi @jcampbell05, thanks for getting in touch. We recently wrote a [post](https://ello.co/sean/post/eobkyhj79p8yzol7it_1ew) about the experience of open sourcing the app. Would something along these lines be interesting as a guest post?

**Comment by jcampbell05** [comment]
Yes that would be great :) 👍
