### ISSUE TITLE
ElloKeys has no member teamId

### ISSUE THREAD

**Issue by AndrewSB** [ello/ello-ios#55]
Doesn't compile on master: 
<img width="720" alt="screen shot 2016-07-13 at 11 10 50 am" src="https://cloud.githubusercontent.com/assets/3814772/16814401/89154f60-48ea-11e6-8659-ddbcbc16c30f.png">

**Comment by colinta** [comment]
I'll check this out.

**Comment by colinta** [comment]
Can you try adding this to the bottom of Podfile?

```ruby
plugin 'cocoapods-keys', {
  project: 'Ello',
  keys: [
    'ClientKey',
    'ClientSecret',
    'CrashlyticsKey',
    'Domain',
    'HttpProtocol',
    'Salt',
    'SegmentKey',
    'TeamId',   # <--- add this
  ]
}
```

**Comment by colinta** [comment]
And then run `pod install`

**Comment by AndrewSB** [comment]
Having a weird error inside the `ello-ios` directory - I'm being told that `pod not found`, but only inside the `ello-ios`.

```
➜  ~ which pod
> /Users/asb/.rvm/gems/ruby-2.3.0/bin/pod
➜  Developer cd Developer 
➜  Developer which pod
> /Users/asb/.rvm/gems/ruby-2.3.0/bin/pod
➜  Developer cd ello-ios 
➜  ello-ios git:(master) ✗ which pod
> pod not found
```

**Comment by colinta** [comment]
That must have something to do with `.ruby-version` being set to 2.2.2. @666 can we remove that file?

**Comment by rynbyjn** [comment]
I think you need to run the `pod` commands with `bundle exec` due to cocoapods being in the `Gemfile`.

**Comment by AndrewSB** [comment]
yup, that worked @rynbyjn!

Maybe add an explanation to the Gemfile? It's probably just me and my lack of a ruby background

**Comment by AndrewSB** [comment]
@colinta no luck.

When I `bundle exec pod install`, the CLI prompts me to enter in a key for `TeamId`, but it didn't affect ElloKeys - still no `teamId`

**Comment by colinta** [comment]
OK, try this in the terminal:

```
bundle exec pod keys set ClientKey SHOULDNOTMATTER Ello
bundle exec pod keys set ClientSecret SHOULDNOTMATTER Ello
bundle exec pod keys set TeamId SHOULDNOTMATTER Ello
bundle exec pod keys set Domain SHOULDNOTMATTER Ello
bundle exec pod keys set HttpProtocol SHOULDNOTMATTER Ello
bundle exec pod keys set Salt SHOULDNOTMATTER Ello
bundle exec pod keys set CrashlyticsKey SHOULDNOTMATTER Ello
```

**Comment by colinta** [comment]
(and then probably `pod install` again)

**Comment by AndrewSB** [comment]
that seems to have done it 😄

thanks @colinta!
