### ISSUE TITLE
Struct vs NSObject for models

### ISSUE THREAD

**Issue by mitchellporter** [ello/ello-ios#65]
Noticed you're using NSObject for your models, instead of structs. Would you mind elaborating why you made that choice? 

Curious to see what your thought process was :)

**Comment by colinta** [comment]
Because structs can't implement `NSCoding`

**Comment by colinta** [comment]
@steam can elaborate 😃

**Comment by steam** [comment]
We **really** wanted to use structs or Swift classes but yeah, what @colinta said. `NSCoding` is a requirement of our persistence library.

**Comment by mitchellporter** [comment]
@colinta @steam Makes sense. You guys have done a really great job with this codebase. I've been writing swift for awhile now but feel like I'm simply writing in the old objc style. This project has been a great inspiration for learning to write "swiftier" code, so thanks for open sourcing this.

I really appreciate it, its one of the best examples I've come across.

**Comment by steam** [comment]
@colinta messaged me because I spent a good week trying to revamp our model layer once only to run up against the `NSCoding` requirement and deleting the branch.

**Comment by mitchellporter** [comment]
@steam Happens to the best of us. If it makes you feel any better you just saved me from making the same mistake ;)

**Comment by steam** [comment]
Thanks @mitchellporter, our hope was that we could help others by contributing our experiences back to the greater swift community. Artsy's [Eidolon](https://github.com/artsy/eidolon) project was a huge help for us getting started. @ashfurrow's work on [Moya](https://github.com/Moya/Moya) was an eye opener. Using enums the way he did heavily informed our approach and helped us start to see things differently than our objective-c brains had previously.

**Comment by mitchellporter** [comment]
@steam Awesome, I'll have to take a closer look at Moya. Am I correct that you are using Moya by itself, and not using its reactive extensions?

**Comment by steam** [comment]
Correct, we don't use any of the reactive extensions or any reactive libraries in the project for that matter.

**Comment by swiftcodex** [comment]
Agreed w/ @mitchellporter, Super swifty! Love the enum-based design. I feel like this repo should win some sort of award. 🏆  

@steam & @colinta Since you are taking random questions from the peanut gallery: Is there an architecture advantage for making a direct Alamofire request in AutoCompleteService? It appears to be the only direct call outside of the router...

**Comment by steam** [comment]
Good question @swiftcodex, I believe it is because we didn't want to go through the heavy lifting of piping that data through our normal parsing pipeline. It was a simple static asset that didn't need the full treatment.

**Comment by steam** [comment]
I'm remembering more now. The normal router expects several pieces of machinery (ie. `StreamKind`). It felt like overkill for the emoji.

**Comment by swiftcodex** [comment]
@steam Very cool. In other projects, I've felt that it would be advantageous to make direct calls outside of the api router in certain scenarios. Extremely glad others feel the same way. May the Swift gods and style guides have mercy upon us. ⚡️
