### ISSUE TITLE
skip and limit for API requests?

### ISSUE THREAD

**Issue by mitchellporter** [ello/ello-ios#75]
I was studying your networking stack the past couple days (great job btw), and one thing I can't seem to figure out is how you guys are handling pagination when making requests to the API.

I'm used to using `skip` and `limit` params to manage this. Am I correct that you're using the`per_page` param to handle the limit of how many objects you want returned to you?

**Comment by rynbyjn** [comment]
Yes `per_page` is how we determine the number of objects returned on any given page. Our API is loosely based off a pre 1.0 release of [jsonapi](http://jsonapi.org/), so our next/prev pagination links are returned through the headers of a given request and used for subsequent pages.

**Comment by mitchellporter** [comment]
> our next/prev pagination links are returned through the headers of a given request and used for subsequent pages.

Thanks for linking that spec info, great stuff. Can you point me to where the `offset` is actually being handled/tracked in the app?

**Comment by mitchellporter** [comment]
@rynbyjn is it handled via ResponseConfig? https://github.com/ello/ello-ios/blob/master/Sources/Networking/ResponseConfig.swift

**Comment by rynbyjn** [comment]
Yes, the `ResponseConfig` is used to store the pagination information and the [`ElloProvider`](https://github.com/ello/ello-ios/blob/master/Sources/Networking/ElloProvider.swift#L416-L442) is what parses that info.

**Comment by mitchellporter** [comment]
Thanks for the help @rynbyjn :)
